config/routes.rb
Rails.application.routes.draw do
  resources :pins

  devise_for :users
  root "pins#index"
  get "about" => "pages#about" # Creates about_path 
  

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "http://www.keley-consulting.com/assets/imageMissing-eb1c8bc863046c027f472df8ad09d7f2.jpg"

validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  validates :image, presence: true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins, dependent: :destroy
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

   def about
  end

end
=begin Ok so to make a new page there are three steps.
One step occurs here and you'll need to have:
def <The name of the new page (eg. Home, About)
end
Two other steps need to be completed in order to create a new page. 
One is in app/views/pages where a new file needs to be made.
The other is in config/routes.rb where a new route needs to be made for the page.
=end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page=> 2)
    # and limit the number of pins to be displayed on the page.
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="container">
      
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <%= link_to "PinterestingApp", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to raw('<span class="glyphicon glyphicon-pushpin"></span> Add a Pin'), new_pin_path %></li>
        <% end %>
        <!-- Just wanted to have the links in this order thats why I've made a new little if the user is signed in block. -->
          <li><%= link_to "Home", root_path %> </li>
          <li><%= link_to "About", about_path %> </li>

      <% if user_signed_in? %>
        <li><%= link_to "Settings", edit_user_registration_path %></li>
         <li>
          <%= link_to "Log out", destroy_user_session_path, method: :delete %> 
        </li>

      <% else %>
      <!--If you wanted to have a second option here (Something else showing when the user was logged out you could put it here. Otherwise you dont even really need the else to be present.) -->
      <li><%= link_to "Log in", new_user_session_path %></li>
      <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div class="container">
   </div class="container">


</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinterestingapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--Code to ensure site looks right on mobile devices -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<%= render 'layouts/header.html.erb' %>

	<!-- Bootstrap code to centre our text -->
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/pages/_home.html.erb
<!--
 Example linking code that was moved to app/views/layouts/application.html.erb/
<%= link_to "Home", root_path %>
<%= link_to "About", about_path %> 
-->
<div class="jumbotron center">
<!-- Ruby links to the Home and About pages. Note root_path and about_path (and all such paths need to be defined in config/route.rb/) -->
	<h1>Welcome to the PinterestingApp</h1>

<% if user_signed_in? %>
<%= link_to 'See Pins', pins_path, class: "btn btn-primary btn-lg" %>
<%= link_to 'New Pin', new_pin_path, class: "btn btn-primary btn-lg" %>

<% else %>

	<!--Added after "#" some code for nice bootstrap buttons-->
		<p> <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg"%>

			<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %> for free!
		</p>
		<% end %>
<!-- Change hyperlink address to sign-up page, Im guessing we'll do that soon but whatevs thought I should get into the habit of writing comments with my code.--> 
<!--Changed hyperlink code from html to embedded Ruby-->
</div>

app/views/pages/about.html.erb
<div class="jumbotron">
	<h1>About Us</h1>
	<p>This is my <a href="http://onemonthrails.com">One Month Rails</a> project. The aim of the project is to create a simple image sharing web application whilst learning the basics of Ruby on Rails. </p>
	<!-- This file was created in app/views/pages file and given the name:
		about.html.erb
	This is one of the three steps needed in order to make a new page.
	-->
</div>

app/views/pages/home.html.erb
<!--
 Example linking code that was moved to app/views/layouts/application.html.erb/
<%= link_to "Home", root_path %>
<%= link_to "About", about_path %> 
-->
<div class="jumbotron center">
<!-- Ruby links to the Home and About pages. Note root_path and about_path (and all such paths need to be defined in config/route.rb/) -->
	<h1>Welcome to the PinterestingApp</h1>

<% if user_signed_in? %>
<%= link_to 'See Pins', pins_path, class: "btn btn-primary btn-lg" %>
<%= link_to 'New Pin', new_pin_path, class: "btn btn-primary btn-lg" %>

<% else %>

	<!--Added after "#" some code for nice bootstrap buttons-->
		<p> <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg"%>

			<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %> for free!
		</p>
		<% end %>
<!-- Change hyperlink address to sign-up page, Im guessing we'll do that soon but whatevs thought I should get into the habit of writing comments with my code.--> 
<!--Changed hyperlink code from html to embedded Ruby-->
</div>

app/views/pins/_editform.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Edit pin</h1>

<%= render 'editform' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.haml
= render 'pages/home' if !user_signed_in?

-# if !user_signed_in? just with the ! makes it a negative. So essentially, if the user is not signed in. Could also use unless without the ! and you'd get the same effect

%div(id="pins" class="transitions-enabled")
  - @pins.each do |pin|
    %div{class: "box panel panel-default"}
      = link_to image_tag(pin.image.url (:medium)), pin
      .panel-body
        = pin.description
        %br
        %strong= pin.user.name if pin.user
          - if current_user && (pin.user == current_user)
          .actions
            = link_to edit_pin_path(pin) do
        %span(class="glyphicon glyphicon-edit") Edit
            = link_to pin, method: :delete, data: { confirm: 'Are you sure?'} do
            %span(class="glyphicon glyphicon-remove") Delete
        
  - if user_signed_in?
    = link_to 'New Pin', new_pin_path
    
.center
   = will_paginate @posts, renderer: BootstrapPagination::Rails

app/views/pins/new.html.haml
%h1 New pin
= render 'form'
= link_to 'Back', pins_path

app/views/pins/show.html.haml
.row
  %div{class: "col-md-offset-5 col-md-8"}
    %div{class: "panel panel-default"}
      %div{class: "panel-heading center"}=image_tag @pin.image.url(:medium)
      .panel-body
      %p
        %strong= @pin.user.name if @pin.user
        %p =@pin.description

      - if @pin.user == current_user
        = link_to edit_pin_path(@pin) do
        %span{class="glyphicon glyphicon-edit"} Edit
      = link_to 'Back', pins_path, class: "btn btn-primary btn-sm"

-# Use the inspect element option when viewing the page in the browser to better see the sizes of the offset and columns
-# You noob. Spell center like this rather than like this (centre)